export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_INFO_FAILD = 'FETCH_USER_INFO_FAILD';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_FAILD = 'FETCH_PRODUCTS_FAILD';

export const FETCH_PRODUCT_EDIT = 'FETCH_PRODUCT_EDIT';
export const CLEAR_PRODUCT_EDITTING = 'CLEAR_PRODUCT_EDITTING';
export const FETCH_COMMENT_PRODUCT_EDIT = 'FETCH_COMMENT_PRODUCT_EDIT';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_FAILD = 'FETCH_POSTS_FAILD';
export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
export const FETCH_POST_COMMENTS_FAILD = 'FETCH_POST_COMMENTS_FAILD';

export const FETCH_PRODUCT_COMMENT = 'FETCH_PRODUCT_COMMENT';
export const FETCH_PRODUCT_COMMENT_FAILD = 'FETCH_PRODUCT_COMMENT_FAILD';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const DELETE_FROM_WISHLIST = 'DELETE_FROM_WISHLIST';

export const UPDATE_CART = 'UPDATE_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY';
export const DELETE_TO_CART = 'DELETE_TO_CART';
export const CLEAR_ALL_FROM_CART = 'CLEAR_ALL_FROM_CART';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const FILTER_BY_RANGE_SLIDER = 'FILTER_BY_RANGE_SLIDER';
export const FILTER_BY_SIZE = 'FILTER_BY_SIZE';
export const CLEAR_FILTER_BY_SIZE = 'CLEAR_FILTER_BY_SIZE';
export const FILTER_BY_RATING = 'FILTER_BY_RATING';
export const CLEAR_RATING = 'CLEAR_RATING';
export const SORT_PRODUCT = 'SORT_PRODUCT';
export const SORT_COMMENT = 'SORT_COMMENT';

export const PLACE_ORDER = 'PLACE_ORDER';
export const FETCH_ORDERS_INFO = 'FETCH_ORDERS_INFO';

export const ADMIN_AUTH = 'ADMIN_AUTH';
